version: '3.3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: finance-tracker
    env_file: .env.local
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - db
    links:
      - db
  db:
     network_mode: host
     image: mysql:5.7.33
     ports:
       - '4306:3306'
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: test_database
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
